### ISSUE TITLE
Bug: scroll bar flicker

### ISSUE THREAD

**Issue by UkoeHB** [UmbraLuminosa/sickle_ui#10]
The scroll bar flickers when spawning a scroll view. Not sure if this is an ordering issue or what.

**Comment by eidloi** [comment]
This is probably because the padding of the content container needs to be adjusted based on the overflow of it (to leave space for the scroll bars). The approach will be changed with the introduction of themes, though this still needs extra care.

Thanks for the report!

**Comment by eidloi** [comment]
This should no longer happen as of v0.2.0, let me know if you still encounter it.
