### ISSUE TITLE
Labels are not visible.

### ISSUE THREAD

**Issue by Dadlord36** [UmbraLuminosa/sickle_ui#100]
For some reason whenever there is a simple Label spawn is requested through a UiBuilder - it won't show up. You can see it in any available examples (like empty tabs are suppose to show a simple message, but it is not there).

**Comment by eidloi** [comment]
This is because the `default_font` feature of bevy is not enabled, so non-styled text is not rendering. I'll add it as a feature flag as well and enable it by default.
