### ISSUE TITLE
Naming conflict with `bevy_mod_picking`

### ISSUE THREAD

**Issue by musjj** [UmbraLuminosa/sickle_ui#104]
Both `bevy_mod_picking` and `sickle_ui` has a struct called `On`:

```rust
use bevy_mod_picking::prelude::On;
use sickle_ui::prelude::On;
```

This makes it painful when you want to use them together. With `bevy_mod_picking` already upstreamed, it might be a good idea to rename the struct to something else.

**Comment by eidloi** [comment]
This is one of the rare cases (that I have seen coming :D) where the names refer to something completely different and both quite specific, thus renaming is difficult (as there is no alternative).
