### ISSUE TITLE
Dependency on bevy_gltf only used in examples

### ISSUE THREAD

**Issue by cephen** [UmbraLuminosa/sickle_ui#109]
Hiya, after adding sickle to a 2D bevy project I've noticed that the `bevy_gltf` feature has been added to my build (and has,  in turn, added a number of other bevy features I do not want or need in this project).
After looking through the repository I can see that this feature is only used in examples. Could this feature be moved into `dev-dependencies`?

**Comment by eidloi** [comment]
Ahoy! Thanks for the finding. The gltf is used by the scene_view dev panel in the main crate, although only indirectly (it spawns a SceneBundle) so yeah it can be a dev dependency!
