### ISSUE TITLE
Scroll not detected over button

### ISSUE THREAD

**Issue by UkoeHB** [UmbraLuminosa/sickle_ui#12]
Buttons inside a scroll view are a black hole for scroll interactions. This is probably more an issue with Bevy's interaction model than `sickle_ui`.

**Comment by eidloi** [comment]
this isn't specific to Bevy actually and it all depends on how focus is captured. I have a component (ScrollThrough) that could be attached to the buttons to force scrolling to pass through them, but I didn't want to automatically do it. Sliders for instance need to capture the scroll themselves even over their button.

**Comment by eidloi** [comment]
> > I have a component (ScrollThrough) that could be attached to the buttons to force scrolling to pass through them, but I didn't want to automatically do it.
> 
> I think it should scroll through by default. It's easy to forget to add this, which means a higher rate of unintended bugs. Opting-in to no-scroll-through means you can do it for specifically those widgets where you want special behavior (and are explicitly testing for it).

yeah I am leaning in that direction as well. Will come back to this when I do a pass on the focus management

**Comment by eidloi** [comment]
> I tried adding `ScrollThrough` to my button with `TrackedInteraction` but it doesn't seem to do anything.

If it's a NodeBundle you need to add `Interaction` manually as well, otherwise the `FluxInteraction` won't work
