### ISSUE TITLE
ComponentThemePlugin is easily forgotten

### ISSUE THREAD

**Issue by UkoeHB** [UmbraLuminosa/sickle_ui#40]
I have forgotten to add `ComponentThemePlugin` multiple times, the UI just silently fails when it's missing.

Alternatives:
- Use a `Command` to insert themes instead of directly inserting them as components. The command can notify a central resource to register newly-encountered themes. The central resource stores oneshots internally in place of the theme systems that are currently registered by `ComponentThemePlugin`. Then there is one exclusive system registered by a normal plugin that iterates through the stored oneshots and calls them against the world. The biggest open question here is the `is_custom` field on the current plugin.
- ??

**Comment by eidloi** [comment]
The `ComponentThemePlugin` is the heart of the theming systems, however it is not the only way to do it. Practically theming is a way to automatically generate, merge, and apply `DynamicStyle` components to entities. No themes are inserted on entities by the plugin, it just contextually runs the `refresh_theme` command. The command will look for theme components on the entity and any of it's ancestors, and finally grabs the default implementation. This means that adding themes on entities is actually the *override* mechanism for themes.

When `is_custom` is set to true the theme update will be done in a schedule after the regular themes are done. This is there so you can manipulate or override `DynamicStyle` once normal theming generated it.

Also the plugin adds systems that monitor changes in to components, theme data, and pseudo states of components it's bound to. You can just generate the `DynamicStyle` directly if you wish to avoid the theming system.

**Comment by eidloi** [comment]
`ComponentThemePlugin` is generic, so it needs to be added per component. If we make in non-generic, we need to use the type registry or the resource you mentioned, which also needs to be added manually. It is also important that theming is opt-in. You do not have to pay the price runtime if you remove the plugins or not use them. You could also create your own plugin to manage your components based on something else (i.e. a macro that generates your content could inject additional entries automatically).

I mean, we could prolly make a plugin slapped on `C: Component + DefaultTheme + UiContext` and pick up everything that defines these, but then you have no option to schedule your update a set later (in the custom set). I have to think about whether this last part really worth cranking out pairs of systems though.
