### ISSUE TITLE
Floating Panel for UiRoot

### ISSUE THREAD

**Issue by alexparlett** [UmbraLuminosa/sickle_ui#48]
Wondering whether floating panel should also be implemented for UiRoot, doesn't seem to make sense to spawn a row or a column to have a single child of floating panel nested underneath it, especially when using it for window style mechanics.

**Comment by eidloi** [comment]
this is probably a leftover from the time there was no UiRoot. I'll check what needs to be done thanks!

**Comment by eidloi** [comment]
The `simple_editor` example now has an instance of this. Note the `TargetCamera` that should be added to root nodes.
