### ISSUE TITLE
sickle_math and sickle_ui_scaffold include all bevy default features

### ISSUE THREAD

**Issue by mystal** [UmbraLuminosa/sickle_ui#72]
I'm adding sickle_ui to my small game and noticed that it added a bunch of dependencies. Taking a closer look, I saw that the `sickle_math` and `sicle_ui_scaffold` crates just include bevy with all its default features, instead of selecting only the ones used. Would it be possible to strip down the bevy features pulled in by sickle_ui to only the ones needed, that way my small 2D game doesn't pull in crates like `bevy_pbr` and `bevy_gltf`?

Thanks!

**Comment by eidloi** [comment]
Absolutely, this is just pure laziness on my part, will fix thanks!

**Comment by eidloi** [comment]
I might go through it one day and weed out really everything unnecessary, but for now I have removed default features. `sickle_math` also got a leaner dep tree now
