### ISSUE TITLE
FloatingPanel cannot be resized

### ISSUE THREAD

**Issue by Peepo-Juice** [UmbraLuminosa/sickle_ui#75]
When I try to resize it, a yellow line appears to highlight the edge of the panel (which is fine), but when i click to resize, it just disappears without letting me resize. The yellow highlight doesn't come back if I try to hover my mouse at the same edge.
 
Reproduce with:
```rust
commands.ui_builder(UiRoot).column(|builder| {
    builder.floating_panel(
        FloatingPanelConfig {
            title: Some("Root floating panel".into()),
            resizable: true,
            ..default()
        },
        FloatingPanelLayout {
            size: Vec2::new(200., 300.),
            position: Vec2::new(100., 100.).into(),
            ..default()
        },
        |_| {},
    );
});
```

Im on Linux (NixOS):
```
[dependencies]
bevy = { version = "0.14", features = ["serialize", "wayland"] }
sickle_ui = "0.2.1"
```

**Comment by eidloi** [comment]
I added a fix for a similar case, could you check with main if this issue is still there for you?

**Comment by eidloi** [comment]
no need, sickle_ui is dead 🗡️
