### ISSUE TITLE
FloatingPanel Title not applying default font

### ISSUE THREAD

**Issue by Peepo-Juice** [UmbraLuminosa/sickle_ui#77]
So far I haven't explicitly set any fonts in sickle, but I do have a different default font set for the whole app. 

To change the default font, i used the solution in this discussion: https://github.com/bevyengine/bevy/discussions/11839

When I spawn a floating panel with a title, it does not use my default font, but if I use inspector-egui to change the title, it applies the correct font. I also noticed it works when messing around with other fields inside FloatingPanelConfig, i.e disabling the foldable field applies the correct font. But if i later fold the panel, the other incorrect font comes back.

Furthermore, to test whether this was specific to FloatingPanels, i also tried doing this in the same context: `builder.label(LabelConfig::from("EXAMPLE".to_string()));` and it applied the default font as expected, so it may just be a FloatingPanel issue.

Im on Linux (NixOS):
```
[dependencies]
bevy = { version = "0.14", features = ["serialize", "wayland"] }
sickle_ui = "0.2.1"
```

**Comment by eidloi** [comment]
`sickle_ui` brings it's own set of fonts and most of the widgets use the fonts defined in `ThemeData`. The `FloatingPanel` title uses `FontStyle::Body, FontScale::Large, FontType::Regular` which is `FiraSans-Regular` in this case.

**Comment by eidloi** [comment]
You can change these btw by changing the `ThemeData` resource
