### ISSUE TITLE
[Feature Request] Optional Contexts Support.

### ISSUE THREAD

**Issue by Aleod-m** [UmbraLuminosa/sickle_ui#79]
I need to have a way to define a contexted themed widget with optional contexts.

A use case of this feature is a Button with either a label or an icon or both. But if one isn't present currently the theme plugin produces a panic as i cannot change the `Entity::PLACEHOLDER` to the corresponding child because it doesn't exist. 

Another use case would be changing the style of a widget depending if it has a "child" or not for tree like structures.

**Comment by eidloi** [comment]
Makes sense, the context is indeed a bit too rigid at the moment. I can probably make it return `Option<Entity>` instead, the issue is with cleanup: devs would need to make sure that once the option returns None (after returning Some) the original target would be cleaned up by them since the theming system can no longer "see" the lost target. Normally this isn't an issue if the original target was despawned, but moving could be an issue.

**Comment by eidloi** [comment]
You could add additional extension fns for each enum or just use a config to decide which variant to spawn. You would need to look out for adding styles to contexts that are not present in the current variant and that hot-swapping variants would work, except the cleanup would be done for the new variant and not the old one.

The main issue with using `Option<Entity>` as context is that it already _is_ an option, but the `None` means "target the main entity". This could be resolved at the cost of the breaking change to the `UiContext` signature, but it is doable.

**Comment by Aleod-m** [comment]
The solution with the enum works just implemented it but its verbose. I had a more scuffed version where i checked if the entities were placeholder but it was error prone and not very 'safe'.

**Comment by eidloi** [comment]
yeah It makes it chonky. I'll look into how to make this better

**Comment by eidloi** [comment]
> This is what I do for widgets with ambiguous context entities: https://github.com/UkoeHB/bevy_cobweb_ui/blob/70d7446952b1a191f12de6ca7aa9498d41ab4d66/src/builtin/widgets/radio_button/mod.rs#L56

That's not a bad idea either!
