### ISSUE TITLE
How to make ScrollView content always at the bottom?

### ISSUE THREAD

**Issue by tungtose** [UmbraLuminosa/sickle_ui#83]
I'm building a chat box and can't figure out how to automatically update the scroll bar when the content changes. I'm having trouble because the ScrollView component's data is private.
![image](https://github.com/user-attachments/assets/9efc99ae-e180-4522-931e-d546cd28a6f8)

**Comment by eidloi** [comment]
It should update automatically based on the content size, more specifically it processes this: `q_content: Query<&ScrollViewContent, Changed<Node>>`. Are you sure you are grabbing the right entity? The scrollview's viewport_id() is not what you want. I recon I can add a getter for the content container as well, but you can capture it when you spawn the container (from inside the callback)

**Comment by eidloi** [comment]
It should update automatically based on the content size, more specifically it processes this: q_content: Query<&ScrollViewContent, Changed<Node>>. Are you sure you are grabbing the right entity? The scrollview's viewport_id() is not what you want. I recon I can add a getter for the content container as well, but you can capture it when you spawn the container (from inside the callback)

**Comment by eidloi** [comment]
@tungtose  whops I think I accidentally deleted your other issue about scrolling! I'll make the needed fields public in a minute, sorry about that!

**Comment by tungtose** [comment]
@eidloi  Yes, the scroll bar currently updates automatically. However, I want the scroll bar to automatically scroll down when new chat content is added.
Is it doable with out public this  `scrollview_offset` field?
![image](https://github.com/user-attachments/assets/2fa85c05-7409-486e-840c-cb2b86187111)

**Comment by eidloi** [comment]
@tungtose currently no, but I am making it public since it is quite common wanting to scroll to a known point. You can just set it to some absurd high number and it will be clamped. I have added a new system set `ScrollViewOffsetUpdate`, you can schedule the setter before this to in-frame scroll over. 

I am also considering adding an auto-scroll-to-the-end flag since terminal containers would want that too, but in your case an eased animation might look better than just snapping there.

**Comment by tungtose** [comment]
I'm stoked! Thanks!

**Comment by eidloi** [comment]
it's on main. I'll do a release later this week with the accumulated fixes

**Comment by tungtose** [comment]
@eidloi Just play it out, It work as expected. Thank you!

This is how I do:
![image](https://github.com/user-attachments/assets/d285658a-3ba3-47c4-a521-4db2d03caae6)
