### ISSUE TITLE
Is sickle_ui_scaffold meant to have `bevy default-features=true`?

### ISSUE THREAD

**Issue by PROMETHIA-27** [UmbraLuminosa/sickle_ui#85]
This seems to be causing `sickle_ui` to pull in every default bevy crate even though it seems like it's unnecessary and for the most part excluded correctly.

**Comment by eidloi** [comment]
Thanks for the report! This is already fixed on main and will be in the next release. I'll do my best to find time to do it this weekend!

**Comment by eidloi** [comment]
ah damn, I thought it was fixed but in fact it was not. The `default-features=true` was left in even though the features are listed...

**Comment by eidloi** [comment]
fixed by #87
